name: cros-im
on:
  push:
    paths:
      - cros-im/**
      - .github/workflows/cros-im.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_DEST: ${{ secrets.S3_DEST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Replace base image for arm64 build
      run: sed -i 's#archlinux:base-devel#agners/archlinuxarm#g' ./.github/actions/build/Dockerfile

    - name: Build Packages
      uses: ./.github/actions/build
      with:
        packages: "${{ github.workflow }}"

    - name: Upload cros-im
      run: find -type f -iname "*.pkg.tar.zst" -exec aws s3 cp {} s3://${S3_DEST}/aarch64/ \;
      working-directory: ${{ github.workflow }}
