name: hishtory
on:
  push:
    paths:
      - hishtory/**
      - .github/actions/build/**
      - .github/workflows/hishtory.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        machine: [x86_64, aarch64]

    runs-on: ${{ matrix.machine == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_DEST: ${{ secrets.S3_DEST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set pkgver to latest release
      run: |
        version=$(curl -s https://api.github.com/repos/ddworken/hishtory/releases/latest | grep -oP '(?<="tag_name"\: "v)[^"]+')
        sed -i "s/@@pkgver@@/$version/g" PKGBUILD
      working-directory: ${{ github.workflow }}

    - name: Replace base image for arm64 build
      if: matrix.machine == 'aarch64'
      run: sed -i 's#archlinux:base-devel#agners/archlinuxarm#g' ./.github/actions/build/Dockerfile

    - name: Build Packages
      uses: ./.github/actions/build
      with:
        packages: "${{ github.workflow }}"

    - name: Upload hishtory
      run: find -type f -iname "*.pkg.tar.zst" -exec aws s3 cp {} s3://${S3_DEST}/${{ matrix.machine }}/ \;
      working-directory: ${{ github.workflow }}
