name: tensorflow
on:
  push:
    paths:
      - tensorflow/*
      - .github/workflows/tensorflow.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'
env:
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}
  BAZEL_CACHE_AUTH: /tmp/sa_key.json
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'willthefrog/makepkg'
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Setup gcloud
      run: |
        echo ${GCP_SA_KEY} | base64 -d > /tmp/sa_key.json
        gcloud auth activate-service-account ${GCP_SA_EMAIL} --key-file=/tmp/sa_key.json
    - name: Update pacman index
      run: pacman -Sy
    - name: Build Package
      continue-on-error: true
      timeout-minutes: 340
      run: |
        chmod 777 -R .
        chmod 777 -R /github/home/
        sudo -E -u arch makepkg -rsf --noconfirm
      working-directory: ${{ github.workflow }}
  finish:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: 'willthefrog/makepkg'
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Setup gcloud
      run: |
        echo ${GCP_SA_KEY} | base64 -d > /tmp/sa_key.json
        gcloud auth activate-service-account ${GCP_SA_EMAIL} --key-file=/tmp/sa_key.json
    - name: Update pacman index
      run: pacman -Sy
    - name: Build Package
      run: |
        chmod 777 -R .
        chmod 777 -R /github/home/
        sudo -E -u arch makepkg -rsf --noconfirm
      working-directory: ${{ github.workflow }}
    - name: Upload Package
      run: |
        gsutil cp *.zst ${GCS_BUCKET}
      working-directory: ${{ github.workflow }}
