name: tensorboard
on:
  push:
    paths:
      - tensorboard/**
      - .github/actions/build/**
      - .github/workflows/tensorboard.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_DEST: ${{ secrets.S3_DEST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Build Packages
      uses: ./.github/actions/build
      with:
        packages: ${{ github.workflow }}

    - name: Upload Package
      run: find -type f -iname "*.pkg.tar.zst" -exec aws s3 cp {} s3://${S3_DEST}/ \;
      working-directory: ${{ github.workflow }}
