name: tfrt
on:
  push:
    paths:
      - tfrt/*
      - .github/workflows/tfrt.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UPTOC_UPLOADER_AK: ${{ secrets.STORAGE_AK }}
      UPTOC_UPLOADER_SK: ${{ secrets.STORAGE_SK }}

    container:
      image: 'archlinux:base-devel'

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Setup user
      run: |
        useradd -Ums /bin/bash arch
        cat > /etc/sudoers.d/passwd <<__EOF__
        ALL ALL = (ALL) NOPASSWD: ALL
        __EOF__

    - name: Install packages
      run: pacman -Sy --noconfirm git

    - name: Build Package
      run: |
        chmod 777 -R .
        sudo -u arch makepkg -risf --noconfirm
      working-directory: ${{ github.workflow }}

    - name: Upload Package
      uses: saltbo/uptoc@master
      with:
        driver: google
        region: auto
        bucket: ${{ secrets.STORAGE_BUCKET }}
        dist: "${{ github.workflow }}/*.zst"
