name: torch
on:
  push:
    paths:
      - torch/**
      - torchvision/**
      - .github/actions/build/**
      - .github/workflows/torch.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up unused tools to save some space
      run: |
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc
        rm -rf "/usr/local/share/boost"
        rm -rf "$AGENT_TOOLSDIRECTORY"

  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_DEST: ${{ secrets.S3_DEST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Build Packages
      uses: ./.github/actions/build
      with:
        packages: "${{ github.workflow }} torchvision"

    - name: Upload torch
      run: find -type f -iname "*.pkg.tar.zst" -exec aws s3 cp {} s3://${S3_DEST}/ \;
      working-directory: torch

    - name: Upload torchvision
      run: find -type f -iname "*.pkg.tar.zst" -exec aws s3 cp {} s3://${S3_DEST}/ \;
      working-directory: torchvision
