name: torch
on:
  push:
    paths:
      - torch/**
      - torchvision/**
      - .github/workflows/torch.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up unused tools to save some space
      run: |
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc
        rm -rf "/usr/local/share/boost"
        rm -rf "$AGENT_TOOLSDIRECTORY"

  build:
    runs-on: ubuntu-latest

    env:
      UPTOC_UPLOADER_AK: ${{ secrets.STORAGE_AK }}
      UPTOC_UPLOADER_SK: ${{ secrets.STORAGE_SK }}

    container:
      image: 'archlinux:base-devel'

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Setup user
      run: |
        useradd -Ums /bin/bash arch
        cat > /etc/sudoers.d/passwd <<__EOF__
        ALL ALL = (ALL) NOPASSWD: ALL
        __EOF__

    - name: Install packages
      run: pacman -Sy --noconfirm git

    - name: Build torch
      run: |
        chmod 777 -R .
        sudo -u arch makepkg -rsfi --noconfirm
      working-directory: ${{ github.workflow }}

    - name: Build torchvision
      run: |
        chmod 777 -R .
        sudo -u arch makepkg -rsf --noconfirm
      working-directory: torchvision

    - name: Upload torch
      uses: saltbo/uptoc@master
      with:
        driver: google
        region: auto
        bucket: ${{ secrets.STORAGE_BUCKET }}
        dist: "${{ github.workflow }}/*.zst"

    - name: Upload torchvision
      uses: saltbo/uptoc@master
      with:
        driver: google
        region: auto
        bucket: ${{ secrets.STORAGE_BUCKET }}
        dist: "torchvision/*.zst"
