name: torch
on:
  push:
    paths:
      - torch/**
      - torchvision/**
      - .github/workflows/torch.yml
  repository_dispatch:
  schedule:
    - cron: '0 18 * * 6'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up unused tools to save some space
      run: |
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc
        rm -rf "/usr/local/share/boost"
        rm -rf "$AGENT_TOOLSDIRECTORY"

  build:
    runs-on: ubuntu-latest

    env:
      RCLONE_S3_PROVIDER: ${{ secrets.S3_PROVIDER }}
      RCLONE_S3_ENV_AUTH: true
      RCLONE_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      RCLONE_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      RCLONE_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      RCLONE_S3_STORAGE_CLASS: STANDARD
      RCLONE_S3_BUCKET: ${{ secrets.S3_BUCKET }}

    container:
      image: 'archlinux:base-devel'

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Setup user
      run: |
        useradd -Ums /bin/bash arch
        cat > /etc/sudoers.d/passwd <<__EOF__
        ALL ALL = (ALL) NOPASSWD: ALL
        __EOF__

    - name: Install packages
      run: pacman -Sy --noconfirm git rclone

    - name: Build torch
      run: |
        chmod 777 -R .
        sudo -u arch makepkg -rsfi --noconfirm
      working-directory: ${{ github.workflow }}

    - name: Build torchvision
      run: |
        chmod 777 -R .
        sudo -u arch makepkg -rsf --noconfirm
      working-directory: torchvision

    - name: Upload torch
      run: |
        rclone copy *.zst :s3:${RCLONE_S3_BUCKET}
      working-directory: ${{ github.workflow }}

    - name: Upload torchvision
      run: |
        rclone copy *.zst :s3:${RCLONE_S3_BUCKET}
      working-directory: torchvision
